# Uncomment the next line to define a global platform for your project
platform :osx, '10.11'

# use_frameworks!

inhibit_all_warnings!

# install! 'cocoapods', generate_multiple_pod_projects: true


target 'DDPlayMacPlayer' do
pod 'AFNetworking'
pod 'Masonry'
pod 'JHDanmakuRender'
pod 'VLCKit'
pod 'CocoaLumberjack'
pod 'DDPShare', :path => '../LocalPods/DDPShare'
pod 'DDPCategory', :path => '../LocalPods/DDPCategory'
end
